// <auto-generated />
namespace Service_Database_Connection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class rty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rty));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211442536_rty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
